-- 로그인/회원가입 BCrypt + JWT 적용용 DB 패치
-- users 테이블이 이미 존재한다는 전제입니다.

ALTER TABLE users
ALTER COLUMN password TYPE VARCHAR(255);

ALTER TABLE users
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;

ALTER TABLE users
ALTER COLUMN status SET DEFAULT 'PENDING';

-- 상태값 정리용. 기존 ACTIVE 계정은 유지하고, NULL만 PENDING 처리합니다.
UPDATE users
SET status = 'PENDING'
WHERE status IS NULL;
